import uuid from "react-native-uuid";

const data = [
  {
    id: uuid.v4(),
    title: "గాయ పడ్డావా - నా కొరకు సిలువలో",
    lyrics: "గాయ పడ్డావా - నా కొరకు సిలువలో\nధూషింప బడ్డావా - నా కొరకు యేసయ్య\n\nనిను అప్పగించిన - నాకోసము\nచెదరి పోయిన - నాకోసము\n\nచేతులు చాపి - క్షమియించి\n\nయేసు - నా రక్షణ \n\n1. శిలలాంటి నా కొరకు - సిలువ పై వ్రేలాడితివి\nకఠిన శిక్షలొ - నన్ను జ్ఞాపకం చేసుకొని\nక్షమియించినావు - నన్ను చేర్చుకున్నావు\nక్షమియించినావు - నన్ను రక్షించి నావు ||యేసు - నా రక్షణ||\n\n2. నలిగిన రెళ్లు వై - చిరిగిన దేహముతో\nముళ్ల మకుటము - రక్త ధారలు\nభరియించినావు - ఆత్మనప్పగించినావు\nభరియించినావు - నన్ను రక్షించి నావు ||యేసు - నా రక్షణ||",
    keywords: ["gaaya paddava naa koraku", "gaya paddava na koraku", "gaaya padava nakosaku", "sam deeven", "satyatej devunuri", "blessy", "good friday", "lent", "goodfriday"],
    video: "",
    artist: "Satyatej Devunuri, Sam Deeven, Blessy",
    genre: ["Good Friday", "Lent"],
    timeSignature: "3/4",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
];

console.log(Object.keys(data).length);
