import uuid from "react-native-uuid";

const data = [
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
  {
    id: uuid.v4(),
    title: "",
    lyrics: "",
    keywords: [],
    video: "",
    artist: "",
    genre: [],
    timeSignature: "",
  },
];

console.log(Object.keys(data).length);
